City-of-Helsinki/drupal-module-helfi-api-base

- src/Commands/LocaleCommands.php
How to test:
- Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/69
- When the one above is approved, you may approve this one as well
> UHF-1023 Translations

- helfi_api_base.info.yml
- helfi_api_base.services.yml
- src/TwigExtension/TwigExtension.php
Instructions are in this PR: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/68
Also check these:
https://github.com/City-of-Helsinki/drupal-hdbt/pull/68
https://github.com/City-of-Helsinki/drupal-helfi/pull/86
> UHF-1089 Units

- src/Commands/LocaleCommands.php
Treat imported translations as customized translations.
> UHF-1336: Translations

- composer.json
- helfi_api_base.install
TODO: Remove filelog dependency once the change is committed to every project.
> Readded filelog dependency

- .github/workflows/ci.yml
- composer.json
- helfi_api_base.info.yml
- helfi_api_base.install
Installed & enabled health_check module
Make sure your instance is up and running on latest dev branch.
- git checkout dev
- git pull
- make fresh
Update the Helfi api base
- composer `require drupal/helfi_api_base:dev-UHF-7942_health_check`
- Run `make drush-updb drush-cr``
- Go to /en/health
- You should get a timestamp as a response
> UHF-7942 health check module

- README.md
Updated the contact email in the README. Nothing to test, just sanity check.
[UHF-8133]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update README.md with new contact email.

- src/Environment/EnvironmentTrait.php
- tests/src/Kernel/LanguageNegotiatorTest.php
Added getCurrentLanguage methods first parameter on tests. Nothing changed.
> UHF-8290: added parameter to tests

- config/schema/helfi_api_base.schema.yml
- documentation/api-accounts.md
- drush.services.yml
- helfi_api_base.services.yml
- src/Commands/ApiAccountCommands.php
- src/Vault/AuthorizationToken.php
- src/Vault/VaultItemInterface.php
- src/Vault/VaultManager.php
- src/Vault/VaultManagerFactory.php
- tests/src/Unit/Vault/VaultManagerTest.php
- https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/127
> UHF-6316: Vault to store external API credentials

- README.md
- documentation/default-languages.md
- helfi_api_base.services.yml
- src/Language/DefaultLanguageResolver.php
- tests/src/Kernel/DefaultLanguagesTest.php
Added default languages as service parameter.
> UHF-8088: Default language resolver and service parameters

- src/Logger/JsonLog.php
- src/Plugin/Filter/LinkConverter.php
- tests/src/Kernel/DefaultLanguagesTest.php
changed FilterInterface from TYPE_MARKUP_LANGUAGE to TYPE_TRANSFORM_REVERSIBLE from link converter, [issue #3307959](https://www.drupal.org/project/editor_button_link/issues/3307959)
> UHF-8388: changed FilterInterface 

- src/Entity/Form/MenuLinkFormTrait.php
- `composer require drupal/helfi_api_base:dev-UHF-9266`
> UHF-9266: Make sure menu title is a required field

- helfi_api_base.install
Skip the module installation procedures if the install hook is run during config import.
> UHF-9256: Install the debug rest config during module install.

- .github/pull_request_template.md
PR collection: https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/565
[UHF-9711]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add PR-template which matches other repositories

- src/ApiClient/ApiResponse.php
- src/Cache/CacheTagInvalidatorInterface.php
- src/Commands/ApiAccountCommands.php
- src/Commands/DeployCommands.php
- src/Commands/LocaleCommands.php
- src/Commands/RevisionCommands.php
- src/Entity/Revision/RevisionManager.php
- src/Environment/EnvironmentResolver.php
- src/Environment/Project.php
- src/Event/MigrationConfigurationEvent.php
- src/EventSubscriber/EnvironmentResponseSubscriber.php
- src/Language/DefaultLanguageResolver.php
- src/Link/InternalDomainResolver.php
- src/Package/HelfiPackage.php
- src/Plugin/Action/MigrationUpdateAction.php
- src/Plugin/Filter/LinkConverter.php
- src/Plugin/migrate/source/HttpSourcePluginBase.php
- src/Vault/VaultManager.php
- tests/src/Kernel/Plugin/Filter/LinkConverterTest.php
- tests/src/Traits/ApiTestTrait.php
- tests/src/Unit/Environment/EnvironmentResolverTest.php
- tests/src/Unit/Package/HelfiPackageTest.php
> UHF-9832: Run phpcbf on helfi_api_base.

- documentation/pubsub-messaging.md
> added some guidelines how to figure out what is going on

- .github/workflows/ci.yml
- phpcs.xml
- phpunit.xml
- src/Annotation/DebugDataItem.php
- src/ApiClient/ApiFixture.php
- tests/src/Unit/ApiClient/ApiFixtureTest.php
See https://github.com/City-of-Helsinki/drupal-gh-actions/blob/main/.github/workflows/module-tests.yml
> UHF-11137: Use same base image for tests

- README.md
- documentation/asset-versioning.md
- helfi_api_base.module
- src/Environment/EnvironmentEnum.php
- src/Environment/ServiceEnum.php
- tests/modules/asset_version_test/asset_version_test.info.yml
- tests/modules/asset_version_test/asset_version_test.libraries.yml
- tests/modules/asset_version_test/asset_version_test.routing.yml
- tests/modules/asset_version_test/src/Controller/Controller.php
- tests/src/Kernel/AssetVersioningTest.php
* Replace HELFI_DEPLOYMENT_IDENTIFIER in libraries.yml with [composer.lock mtime](https://github.com/City-of-Helsinki/drupal-helfi-platform/blob/main/public/sites/default/settings.php#L413-L421).
* Enable varnish composer profile
* `composer require drupal/helfi_api_base:dev-UHF-11009`
* `make fresh`
* Run `make drush-cr`
* Link to other PR
[UHF-11009]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11009: Replace HELFI_DEPLOYMENT_IDENTIFIER in libraries.yml

- helfi_api_base.services.yml
- src/Features/FeatureManager.php
- src/Features/FeatureManagerInterface.php
* Added interface for the FeatureManager
[UHF-11178]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11178: Interface for the FeatureManager

- src/Environment/ActiveProjectRoles.php
- src/Environment/EnvironmentResolver.php
- src/Environment/Project.php
- tests/src/Unit/Environment/ActiveProjectRolesTest.php
- tests/src/Unit/Environment/ProjectTest.php
* Add paatokset URLs to environment resolver.
[UHF-11699]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11699: Add paatokset to environment resolver

- README.md
- documentation/user-expire.md
- helfi_api_base.module
- src/UserExpire/QueryFilter.php
- src/UserExpire/UserExpireManager.php
- tests/src/Kernel/UserExpire/UserExpireManagerTest.php
* Inactive users are deleted after 5 years.
* Session (cookie lifetime) is limited to 36 hours
- `composer require drupal/helfi_api_base:dev-UHF-11569 drupal/helfi_tunnistamo:dev-UHF-11569 drupal/helfi_proxy:dev-UHF-11569`
- `drush cr`
* https://github.com/City-of-Helsinki/drupal-module-helfi-tunnistamo/pull/49
* https://github.com/City-of-Helsinki/drupal-module-helfi-proxy/pull/81
[UHF-11569]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11569: Delete users after 5 years

- src/ServiceMap/Controller/AutocompleteController.php
https://sentry.hel.fi/organizations/city-of-helsinki/issues/93953
> SENTRY-93953: Fix sentry issue
