City-of-Helsinki/drupal-module-helfi-api-base

- src/Commands/LocaleCommands.php
Prevents overriding existing translations when drush helfi:locale-import command is executed.
> UHF-2723 prevent translation override

- .github/workflows/ci.yml
- .sonarcloud.properties
- config/optional/rest.resource.helfi_debug_data.yml
- config/optional/rest.resource.helfi_debug_package_version.yml
- documentation/debug.md
- helfi_api_base.install
- helfi_api_base.services.yml
- phpunit.xml
- src/Exception/InvalidPackageException.php
- src/Package/HelfiPackage.php
- src/Package/Version.php
- src/Package/VersionChecker.php
- src/Package/VersionCheckerInterface.php
- src/Plugin/DebugDataItem/Composer.php
- src/Plugin/rest/resource/DebugDataResource.php
- src/Plugin/rest/resource/PackageVersion.php
- tests/src/Kernel/ApiKernelTestBase.php
- tests/src/Kernel/Plugin/rest/resource/PackageVersionTest.php
- tests/src/Traits/ApiTestTrait.php
- tests/src/Unit/ComposerDataItemTest.php
- tests/src/Unit/DebugDataResourceDependencyTest.php
- tests/src/Unit/InternalDomainResolverTest.php
- tests/src/Unit/Package/HelfiPackageTest.php
To test this:
- Run `composer require drupal/helfi_api_base:dev-UHF-4788`
- Run `drush updb`
- Send request to `/api/v1/package?name=drupal/helfi_api_base&version=2.1.1`
> UHF-4788: Rest endpoint to check helfi package versions

- config/schema/helfi_api_base.schema.yml
- helfi_api_base.services.yml
- src/EventSubscriber/EnvironmentResponseSubscriber.php
- tests/src/Kernel/EnvironmentResponseSubscriberTest.php
To test this:
- `composer require drupal/helfi_api_base:dev-UHF-X-add-environment-to-response`
- `drush cr`
Check response headers (devtools network tab) and make sure X-Drupal-Instance and X-Drupal-Environment headers are set.
> Add environment and instance name to response headers

- README.md
- composer.json
- config/optional/rest.resource.helfi_debug_data.yml
- config/optional/rest.resource.helfi_debug_package_version.yml
- config/schema/helfi_api_base.schema.yml
- documentation/api-accounts.md
- documentation/deploy-hooks.md
- drush.services.yml
- helfi_api_base.install
- helfi_api_base.module
- helfi_api_base.services.yml
- src/Commands/DeployCommands.php
- src/Environment/EnvMapping.php
- src/Environment/Environment.php
- src/Environment/EnvironmentEnum.php
- src/Environment/EnvironmentResolver.php
- src/Environment/EnvironmentResolverInterface.php
- src/Environment/Project.php
- src/EventSubscriber/DeployHookEventSubscriberBase.php
- src/EventSubscriber/EnsureApiAccountsSubscriber.php
- src/Plugin/DebugDataItem/Composer.php
- src/Plugin/DebugDataItem/MaintenanceMode.php
- src/Plugin/rest/resource/DebugDataResource.php
- src/Plugin/rest/resource/PackageVersion.php
- tests/src/Functional/InstallTest.php
- tests/src/Kernel/EnsureApiAccountsSubscriberTest.php
- tests/src/Kernel/Plugin/DebugDataItem/MaintenanceModeTest.php
- tests/src/Unit/EnvironmentResolverTest.php
- [UHF-6316](https://helsinkisolutionoffice.atlassian.net/browse/UHF-6316)
- [UHF-8059](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8059)
* `git checkout UHF-X-list-of-envs`
* Add this to your `local.settings.php`: 
```
$config['helfi_api_base.api_accounts']['accounts'] = [
['username' => 'helfi-debug-data', 'password' => '123', 'roles' => ['debug_api']],
];
```
* Run `drush cr` and `drush updb`
* Run `drush helfi:post-deploy`
[UHF-6316]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UHF-6316]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
> Added enum to list all available environment names, maintenance mode debug plugin, API account mapper

- fixtures/environments.json
Fix wrong proxy route for kasko. It messed up kasko mobile js menu.
You can reproduce the problem by opening Kasko-site, set it on mobile size and open the mobile menu. You should get JS error on browser console and the url should have `#menu` on it. This indicates that fallback menu is used instead of js menu. You can reproduce this currently on testing and production.
How to test:
[Setup global navigation as described here KASKO being the other site](https://github.com/City-of-Helsinki/drupal-module-helfi-navigation/blob/main/README.md#local-development) 
After kasko has been set up and global navigation works
- Set site on mobile size
- Click the mobile hamburger menu
- Check the site url: it should not have `#menu` in it (`#menu` in site url means that fallback menu is used instead of …
> kasvatus-koulutus to kasvatus-ja-koulutus

- composer.json
- src/Entity/Form/MenuLinkFormTrait.php
- src/EventSubscriber/MigrationSubscriber.php
- src/Plugin/migrate/source/HttpSourcePluginBase.php
- tests/modules/entity_changed_test/entity_changed_test.info.yml
- tests/modules/helfi_locale_test/helfi_locale_test.info.yml
- tests/modules/remote_entity_test/remote_entity_test.info.yml
- tests/src/Kernel/MigrationSubscriberTest.php
- tests/src/Unit/ComposerDataItemTest.php
- tests/src/Unit/DebugDataResourceTest.php
- tests/src/Unit/Package/HelfiPackageTest.php
- tests/themes/link_template_test_theme/link_template_test_theme.info.yml
Added access check to entity queries
Guzzle::jsonDecode to utils::jsonDecode
ProphesizeTrait for prophesize method
How to test:
- composer require drupal/helfi_api_base:dev-UHF-8390
- `composer require drupal/upgrade_status` and `drush en -y upgrade_status`
- run `drush upgrade_status:analyze helfi_api_base`
You should only see deprecation errors from prophecy / prophesize method.
> UHF-8390 D10 depracation updates

- src/Environment/EnvironmentResolver.php
Issue: https://helsinkisolutionoffice.atlassian.net/browse/PLATTA-4937
Refactor computation logic to retrieve only one time the config for active project and active environment.
> compute only once for active project and active env name

- documentation/migrate.md
- drush.services.yml
- src/Commands/MigrateHookCommands.php
- src/EventSubscriber/MigrationSubscriber.php
- src/Logger/JsonLog.php
- tests/src/Kernel/DefaultLanguagesTest.php
- tests/src/Unit/Commands/MigrateHookCommandsTest.php
- `composer require drupal/helfi_api_base:dev-UHF-6542`
- `drush cr`
- Run migration using `--interval` flag. For example `drush migrate:import tpr_service --interval 60` and make sure the migration is run
- Re-run migration using same command and make sure the migration is skipped
- Set migration state to importing: `drush php-eval "\Drupal::keyValue('migrate_status')->set('tpr_service', 1);"`
- Run migration using `--reset-threshold` flag. For example `drush migrate:import tpr_service --reset-threshold 1232313` and make sure migration fails with `[error]  Migration tpr_service is busy with another operation: Importing` error message
- Re-run migration using lower threshold, for example `drush migrate:import tpr_service --reset-threshold 1` and make sure migration status is reset back to …
> UHF-6542: Added generic hooks to skip/reset migrations

- helfi_api_base.module
Set up site normally
Reproduce error:
- `make shell`, run `drush cron`
- At some point you should see an error about email sending
- Run `drush cron` again. 
- You should see the same error again 
Fix:
- `composer require drupal/helfi_api_base:dev-UHF-8945_disable_email`
- Run `drush cr`
- Run `drush cron`
- The error is not shown anymore
> UHF-8945: disable email sending. 

- src/Entity/Form/MenuLinkFormTrait.php
- tests/src/Functional/MenuLinkFormTest.php
See https://helsinkisolutionoffice.atlassian.net/browse/UHF-6294
- `composer require drupal/helfi_api_base:dev-UHF-6294`
> UHF-6294: Allow weight to be changed

- README.md
- config/schema/helfi_api_base.schema.yml
- documentation/revisions.md
- drush.services.yml
- helfi_api_base.install
- helfi_api_base.module
- helfi_api_base.services.yml
- src/Commands/RevisionCommands.php
- src/Entity/Revision/RevisionManager.php
- src/Plugin/QueueWorker/RevisionQueue.php
- tests/modules/remote_entity_test/src/Entity/RemoteEntityTest.php
- tests/src/Kernel/Entity/Revision/RevisionManagerTest.php
- tests/src/Unit/Commands/RevisionCommandsTest.php
- tests/src/Unit/Plugin/QueueWorker/RevisionQueueTest.php
- `composer require drupal/helfi_api_base:dev-UHF-7324`
- `drush cr`
- Add this to your `local.settings.php` file:
```php
$config['helfi_api_base.delete_revisions']['entity_types'] = [
'node',
'paragraph',
'tpr_unit',
'tpr_service',
'tpr_errand_service',
];
```
> UHF-7324: Support deleting old revisions

- README.md
Check the README that the email drupal@hel.fi is no longer in there.
> UHF-8255: Remove email from contact section that is no longer used

- composer.json
* Azure pipeline fails to deploy Drupal 10 update. This attempts to fix the crash:
```
Error: Class "Webmozart\Assert\Assert" not found in /var/www/html/public/modules/contrib/helfi_api_base/src/Vault/VaultManager.php on line 30 #0 /var/www/html/public/modules/contrib/helfi_api_base/src/Vault/VaultManagerFactory.php(46): Drupal\helfi_api_base\Vault\VaultManager->__construct()
```
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113: Drupal 10 support

- helfi_api_base.links.menu.yml
- helfi_api_base.routing.yml
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/171
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/155
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/928
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/717
> UHF-8908: Group HELfi entity types under one link

- src/Commands/LocaleCommands.php
Added override flag to helfi:locale-import to actually override the translations.
> UHF-9088: Helfi locale-import

- src/Language/DefaultLanguageResolver.php
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/773
[UHF-9708]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9708: Add type argument to getCurrentOrFallbackLanguage

- helfi_api_base.install
- helfi_api_base.module
* Enable sentry JS tracking.
* `git checkout dev`
* `make fresh`
* Run `composer require drupal/helfi_api_base:dev-UHF-9982-js-sentry`
* Get Sentry DSN from https://sentry.test.hel.ninja/settings/city-of-helsinki/projects/helfi-core-javascript/keys/.
* Add to compose.yaml
```diff
diff --git a/compose.yaml b/compose.yaml
index 99f55b2..2e408f2 100644
--- a/compose.yaml
+++ b/compose.yaml
@@ -31,6 +31,11 @@ services:
DRUPAL_VARNISH_PORT: 6081
REDIS_HOST: redis
PROJECT_NAME: "${PROJECT_NAME}"
+    SENTRY_DSN: xyz
+    SENTRY_DSN_REACT: xyz
+    SENTRY_DSN_PUBLIC: xyz
+    SENTRY_ENVIRONMENT: 'local'
+    SENTRY_RELEASE: 'dev'
extra_hosts:
- "host.docker.internal:host-gateway"
- "${DRUPAL_HOSTNAME}:host-gateway"
```
* Run `make …
> UHF-9982: Overwrite sentry DSN for js tracking

- src/HelfiApiBaseServiceProvider.php
- tests/src/Unit/Commands/PubSubCommandsTest.php
- tests/src/Unit/Commands/RevisionCommandsTest.php
* Add raven monolog handler: https://git.drupalcode.org/project/raven\#monolog-module-integration.
* Add Sentry environment variables to `compose.yaml`
* `composer require drupal/helfi_api_base:dev-UHF-10844-sentry-logging`
* `make fresh`
* Link to other PR
[UHF-10844]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10844 & UHF-10842: Add raven monolog logger

- src/HelfiApiBaseServiceProvider.php
Raven [README.md](https://git.drupalcode.org/project/raven/-/blob/6.x/README.md?ref_type=heads) asks to disable `message_placeholder` and `filter_backtrace` processors. However, these cause Monolog Lineformatter::format to consume excessive memory when processing log messages with long stack traces.
Adding these back don't seem to cause any problems, and the processors seem to drastically reduce logger memory usage.
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/186
[UHF-10944]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10944: Add sentry logger back

- composer.json
- config/schema/elasticsearch_connector.connector.helfi_connector.schema.yml
- src/Plugin/ElasticSearch/Connector/HelfiConnector.php
- tests/src/Functional/ElasticsearchConnectorTest.php
- tests/src/Kernel/ElasticsearchConnectorTest.php
Related to https://helsinkisolutionoffice.atlassian.net/browse/UHF-10549.
Service addresses use self signed sertificate. To use them, we need to configure elasticsearch_connector module such that it accepts these sertificates.
Run: `composer require drupal/helfi_api_base:dev-UHF-10990`.
In infofinland, add 
```
$config['search_api.server.default']['backend_config']['connector'] = 'basicauth';
$config['search_api.server.default']['backend_config']['connector_config']['url'] = 'https://self-signed.badssl.com/';
$config['search_api.server.default']['backend_config']['connector_config']['username'] = '123';
$config['search_api.server.default']['backend_config']['connector_config']['password'] = '456';
```
to `local.settings.php`.
https://drupal-infofinland.docker.so/admin/config/search/search- …
> Add elasticsearch connector plugin

- helfi_api_base.install
* Added an update hook to remove non-breaking spaces, any leading or trailing `%20` and spaces from link urls.
* Make sure your instance is up and running on latest dev branch.
* `git pull origin dev`
* `make fresh`
* Update the Helfi API Base
* `composer require drupal/helfi_api_base:dev-UHF-10969`
* Run `make drush-cr`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/854
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/174
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/191
[UHF-10969]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10969: Remove leading/trailing spaces

- helfi_api_base.install
Update hooks fails on paatokset: https://github.com/City-of-Helsinki/helsinki-paatokset/actions/runs/12369282693/job/34520859820.
[UHF-10713]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10713: Fix update hook if module is not installed of config is missing

- src/Entity/RemoteEntityBase.php
- src/Entity/RemoteEntityInterface.php
- src/Entity/RevisionController.php
- tests/src/Kernel/Entity/Access/RemoteEntityAccessTest.php
- tests/src/Kernel/Entity/Access/RemoteEntityAccessTestBase.php
https://github.com/City-of-Helsinki/helsinki-paatokset/pull/544
[UHF-10565]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10565: Make RemoteEntityAccessTest extendable

- src/Entity/Revision/RevisionManager.php
This error was most likely caused by database replacer.
[UHF-11480]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11480: Why revision could not be found

- helfi_api_base.info.yml
- src/Environment/Project.php
- translations/fi.po
- translations/sv.po
* Added contexts to project labels.
* Translated drupal instance names.
* `git checkout UHF-12125`
* `make fresh`
* Run `make drush-cr drush-locale-update`
* tbd
[UHF-12125]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-12125 Project label contexts and translations

- src/Environment/Project.php
* Updated Project name for GRANTS to match the value used in Openshift environments: https://dev.azure.com/City-of-Helsinki/avustusasiointi/_git/avustusasiointi-pipelines?path=/components/drupal/openshift-templates/drupal-config-map.yml&version=GBmaster&line=16&lineEnd=17&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents . If the values do not match the environment resolver does not work as expected.
* 
[UHF-12039]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-12039: Updating Project name for grants
